<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>http_dll_2_3</AssemblyName>
    <TargetFramework>net10.0</TargetFramework>
    <RuntimeIdentifier>win-x86</RuntimeIdentifier>
    <PublishAot>true</PublishAot>
    <NativeLib>Shared</NativeLib>
    <SelfContained>true</SelfContained>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\http_dll_2_3_x64\Exports.cs" Link="Exports.cs" />
  </ItemGroup>
</Project>
